import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { stripAttribution, hasAttribution } from '../scripts/strip-attribution.mjs';

const PR_BODY = `## What changed

Adds a release workflow.

## Checklist

- [x] Tests pass

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01TJmP966w9jAcZRCmUB7bDN
`;

test('removes the PR footer and session link', () => {
  const clean = stripAttribution(PR_BODY);
  assert.equal(clean, '## What changed\n\nAdds a release workflow.\n\n## Checklist\n\n- [x] Tests pass\n');
  assert.equal(hasAttribution(clean), false);
});

test('removes commit trailers and the comment footer', () => {
  const text = 'Fix the thing\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_abc123\n';
  assert.equal(stripAttribution(text), 'Fix the thing\n');
  assert.equal(stripAttribution('Done.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n'), 'Done.\n');
});

test('keeps other co-authors, links and rules', () => {
  const text = 'Body\n\n---\n\nMore\n\nCo-authored-by: dependabot[bot] <bot@example.com>\nSee https://claude.ai/code for docs.\n';
  assert.equal(stripAttribution(text), text);
  assert.equal(hasAttribution(text), false);
});

test('keeps a human co-author named Claude', () => {
  const text = 'Pair work\n\nCo-Authored-By: Claude Smith <claude@example.com>\n';
  assert.equal(hasAttribution(text), false);
  assert.equal(stripAttribution(text), text);
});

test('leaves text without attribution untouched, trailing rule included', () => {
  assert.equal(stripAttribution('Body\n\n---\n'), 'Body\n\n---\n');
});

test('keeps a rule that is not directly above the removed footer', () => {
  const text = 'Intro\n\n---\n\nNotes\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n<!-- bot summary -->\n';
  assert.equal(stripAttribution(text), 'Intro\n\n---\n\nNotes\n\n<!-- bot summary -->\n');
});

test('is idempotent and handles an empty body', () => {
  assert.equal(stripAttribution(stripAttribution(PR_BODY)), stripAttribution(PR_BODY));
  assert.equal(stripAttribution(''), '');
});

test('CLI rejects unknown options and missing files with exit 2', () => {
  const script = fileURLToPath(new URL('../scripts/strip-attribution.mjs', import.meta.url));
  for (const args of [['--chek', 'body.md'], [], ['--check'], ['a.md', 'b.md']]) {
    const { status } = spawnSync(process.execPath, [script, ...args]);
    assert.equal(status, 2, `args: ${args.join(' ')}`);
  }
});
