import { test } from 'node:test';
import assert from 'node:assert/strict';
import { stripAttribution, hasAttribution } from '../scripts/strip-attribution.mjs';

const PR_BODY = `## What changed

Adds a release workflow.

## Checklist

- [x] Tests pass

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01TJmP966w9jAcZRCmUB7bDN
`;

test('removes the PR footer and session link', () => {
  const clean = stripAttribution(PR_BODY);
  assert.equal(clean, '## What changed\n\nAdds a release workflow.\n\n## Checklist\n\n- [x] Tests pass\n');
  assert.equal(hasAttribution(clean), false);
});

test('removes commit trailers and the comment footer', () => {
  const text = 'Fix the thing\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_abc123\n';
  assert.equal(stripAttribution(text), 'Fix the thing\n');
  assert.equal(stripAttribution('Done.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n'), 'Done.\n');
});

test('keeps other co-authors, links and rules', () => {
  const text = 'Body\n\n---\n\nMore\n\nCo-authored-by: dependabot[bot] <bot@example.com>\nSee https://claude.ai/code for docs.\n';
  assert.equal(stripAttribution(text), text);
  assert.equal(hasAttribution(text), false);
});

test('is idempotent and handles an empty body', () => {
  assert.equal(stripAttribution(stripAttribution(PR_BODY)), stripAttribution(PR_BODY));
  assert.equal(stripAttribution(''), '');
});
