// Generates dist/figma/push-variables.js: a self-contained Figma Plugin API script that creates or
// updates the MCSS-Lite variables in whatever Figma file it runs in. No account, team or file IDs.
// Run it with any Figma MCP agent (use_figma) or a scripting plugin that supports top-level await.
import { isAlias, aliasPath, isFigmaExcluded, resolve, tokensForMode } from './tokens.mjs';

const COLLECTIONS = { primitive: 'MCSS-Lite / Primitives', semantic: 'MCSS-Lite / Semantic', component: 'MCSS-Lite / Component' };

export function figmaScopes(t, type) {
  if (t.extensions['com.figma.scopes']) return t.extensions['com.figma.scopes'];
  const p = t.path;
  if (p.startsWith('space.')) return ['GAP', 'WIDTH_HEIGHT'];
  if (p.startsWith('border-radius.') || p.endsWith('.radius')) return ['CORNER_RADIUS'];
  if (p.startsWith('border-width.')) return ['STROKE_FLOAT'];
  if (p.startsWith('font.size.')) return ['FONT_SIZE'];
  if (p.startsWith('font.weight.')) return ['FONT_WEIGHT'];
  if (p.startsWith('font.family.')) return ['FONT_FAMILY'];
  if (p.startsWith('container.')) return ['WIDTH_HEIGHT'];
  if (type === 'color') return ['ALL_FILLS', 'STROKE_COLOR'];
  return [];
}

const figmaName = (path) => path.replace(/\.\$root$/, '.default').replace(/\$root/g, 'default').split('.').join('/');
const rgba = (c) => ({ r: c.components[0], g: c.components[1], b: c.components[2], a: c.alpha ?? 1 });
const px = (d) => (d.unit === 'rem' ? +(d.value * 16).toFixed(3) : d.value);

function literal(type, v) {
  switch (type) {
    case 'color': return { type: 'COLOR', value: rgba(v) };
    case 'dimension': return { type: 'FLOAT', value: px(v) };
    case 'number':
    case 'fontWeight': return { type: 'FLOAT', value: v };
    case 'duration': return { type: 'FLOAT', value: v.value };
    case 'fontFamily': return { type: 'STRING', value: Array.isArray(v) ? v[0] : v };
    default: return null; // shadow, cubicBezier: not variables
  }
}

export function buildFigmaScript(pkg, sets) {
  const light = tokensForMode(sets, 'light');
  const dark = tokensForMode(sets, 'dark');
  const collectionOf = (tier) => COLLECTIONS[tier];
  const vars = { primitive: [], semantic: [], component: [] };
  const effects = [];

  const entry = (t, byPathByMode) => {
    const modes = Object.keys(byPathByMode);
    const values = {};
    let type = null;
    for (const m of modes) {
      const byPath = byPathByMode[m];
      const tok = byPath.get(t.path);
      const r = resolve(tok, byPath);
      if (isAlias(tok.value)) {
        const target = byPath.get(aliasPath(tok.value));
        if (isFigmaExcluded(target) || !literal(r.type, r.value)) return null;
        values[m] = { alias: `${collectionOf(target.tier)}::${figmaName(target.path)}` };
      } else {
        const lit = literal(r.type, r.value);
        if (!lit) return null;
        values[m] = lit.value;
      }
      type = literal(r.type, r.value)?.type ?? type;
    }
    const r = resolve(t, byPathByMode[modes[0]]);
    return {
      name: figmaName(t.path),
      type,
      css: t.name,
      ...(t.description && { description: t.description }),
      scopes: figmaScopes(t, r.type),
      values,
    };
  };

  for (const t of sets.primitive) {
    if (t.type === 'shadow') { effects.push(shadowStyle(t.name, t.value)); continue; }
    if (isFigmaExcluded(t) && t.type !== 'fontFamily') continue;
    const e = entry(t, { Value: light });
    if (e) vars.primitive.push(e);
  }
  const semanticAll = [...sets.semantic, ...sets.light];
  for (const t of semanticAll) {
    if (resolve(t, light).type === 'shadow') {
      effects.push(shadowStyle(`${t.name} (light)`, resolve(t, light).value));
      effects.push(shadowStyle(`${t.name} (dark)`, resolve(dark.get(t.path), dark).value));
      continue;
    }
    const e = entry(t, { Light: light, Dark: dark });
    if (e) vars.semantic.push(e);
  }
  for (const t of sets.component) {
    const e = entry(t, { Value: light });
    if (e) vars.component.push(e);
  }

  const data = {
    package: `${pkg.name}@${pkg.version}`,
    collections: [
      { name: COLLECTIONS.primitive, modes: ['Value'], variables: vars.primitive },
      { name: COLLECTIONS.semantic, modes: ['Light', 'Dark'], variables: vars.semantic },
      { name: COLLECTIONS.component, modes: ['Value'], variables: vars.component },
    ],
    effectStyles: effects,
  };

  return `// MCSS-Lite -> Figma variables. GENERATED by scripts/build.mjs; do not edit.
// ${data.package}
// Creates or updates, by name, in the Figma file it runs in:
//   ${COLLECTIONS.primitive} (1 mode), ${COLLECTIONS.semantic} (Light, Dark), ${COLLECTIONS.component} (1 mode),
//   plus effect styles for shadows. Aliases, scopes, descriptions and CSS code syntax are set.
// Safe to re-run: existing variables are updated in place, nothing is deleted.
// Run with any Figma MCP agent ("run dist/figma/push-variables.js in <file URL>") or a scripting plugin.
const DATA = ${serialize(data)};

const report = { collections: {}, created: 0, updated: 0, aliases: 0, effectStyles: 0, warnings: [] };
const byKey = new Map();
const localCollections = await figma.variables.getLocalVariableCollectionsAsync();
const localVariables = await figma.variables.getLocalVariablesAsync();

for (const spec of DATA.collections) {
  let col = localCollections.find((c) => c.name === spec.name);
  if (!col) col = figma.variables.createVariableCollection(spec.name);
  const modeIds = {};
  spec.modes.forEach((modeName, i) => {
    let mode = col.modes.find((m) => m.name === modeName);
    if (!mode && i === 0 && col.modes.length === 1 && !spec.modes.includes(col.modes[0].name)) {
      col.renameMode(col.modes[0].modeId, modeName);
      mode = col.modes[0];
    }
    if (!mode) {
      try { col.addMode(modeName); mode = col.modes.find((m) => m.name === modeName); }
      catch (e) { report.warnings.push(\`\${spec.name}: could not add mode "\${modeName}" (\${e.message}). Your plan may allow fewer modes; those values were skipped.\`); }
    }
    if (mode) modeIds[modeName] = mode.modeId;
  });
  const existing = new Map(localVariables.filter((v) => v.variableCollectionId === col.id).map((v) => [v.name, v]));
  for (const v of spec.variables) {
    let variable = existing.get(v.name);
    if (variable && variable.resolvedType !== v.type) {
      report.warnings.push(\`\${spec.name}/\${v.name}: type changed from \${variable.resolvedType} to \${v.type}; recreated.\`);
      variable.remove();
      variable = null;
    }
    if (variable) report.updated++;
    else { variable = figma.variables.createVariable(v.name, col, v.type); report.created++; }
    variable.description = v.description ?? '';
    variable.scopes = v.scopes;
    variable.setVariableCodeSyntax('WEB', \`var(\${v.css})\`);
    byKey.set(\`\${spec.name}::\${v.name}\`, { variable, spec: v, modeIds });
  }
  report.collections[spec.name] = { modes: Object.keys(modeIds), variables: spec.variables.length };
}

// Literal values first, then aliases (targets now exist).
for (const pass of ['literal', 'alias']) {
  for (const { variable, spec, modeIds } of byKey.values()) {
    for (const [modeName, value] of Object.entries(spec.values)) {
      const modeId = modeIds[modeName];
      if (!modeId) continue;
      const isAliasValue = value && typeof value === 'object' && 'alias' in value;
      if ((pass === 'alias') !== isAliasValue) continue;
      if (isAliasValue) {
        const target = byKey.get(value.alias);
        if (!target) { report.warnings.push(\`\${spec.name}: alias target \${value.alias} missing\`); continue; }
        variable.setValueForMode(modeId, figma.variables.createVariableAlias(target.variable));
        report.aliases++;
      } else {
        variable.setValueForMode(modeId, value);
      }
    }
  }
}

const styles = await figma.getLocalEffectStylesAsync();
for (const s of DATA.effectStyles) {
  let style = styles.find((x) => x.name === s.name);
  if (!style) style = figma.createEffectStyle();
  style.name = s.name;
  style.description = s.description;
  style.effects = s.effects;
  report.effectStyles++;
}

return report;
`;
}

// One variable or style per line, so the file stays reviewable and diff-friendly.
function serialize(data) {
  const list = (items) => `[\n${items.map((i) => `    ${JSON.stringify(i)}`).join(',\n')}\n  ]`;
  const cols = data.collections.map((c) => `{"name":${JSON.stringify(c.name)},"modes":${JSON.stringify(c.modes)},"variables":${list(c.variables)}}`);
  return `{\n"package":${JSON.stringify(data.package)},\n"collections":[\n${cols.join(',\n')}\n],\n"effectStyles":${list(data.effectStyles)}\n}`;
}

function shadowStyle(cssName, value) {
  const layers = Array.isArray(value) ? value : [value];
  return {
    name: `MCSS-Lite/${cssName.replace(/^--/, '').replace(/-/g, ' ').replace(/^shadow /, 'shadow/')}`,
    description: `var(${cssName.replace(/ \((light|dark)\)$/, '')})`,
    effects: layers.map((l) => ({
      type: 'DROP_SHADOW',
      color: rgba(l.color),
      offset: { x: l.offsetX.value, y: l.offsetY.value },
      radius: l.blur.value,
      spread: l.spread?.value ?? 0,
      visible: true,
      blendMode: 'NORMAL',
    })),
  };
}
