// Generates every derived file from tokens/*.json and components/*.json.
// Returns a Map of repo-relative path -> file content. Deterministic: no timestamps.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  loadTokens, tokensForMode, tokenToCss, resolvedCss, isAlias, aliasPath, isFigmaExcluded, MODES,
} from './tokens.mjs';
import { loadContracts, loadExamples } from './contracts.mjs';
import { buildDemo } from './demo.mjs';
import { buildFigmaScript } from './figma-script.mjs';

export const RULES = [
  {
    id: 'golden-rule',
    title: 'Components never set their own outer margin',
    text: 'Never add margin to a c-* root element. Put components inside a layout primitive (l-stack, l-cluster, l-grid, l-sidebar, l-switcher) and let it provide the spacing.',
  },
  {
    id: 'lookup-order',
    title: 'Layout, then component, then utility, then token',
    text: 'Solve a need with an l-* layout primitive first, then a c-* component and its modifiers, then a u-* utility. Only write custom CSS as a last resort, and then use var(--token) values only.',
  },
  {
    id: 'no-invention',
    title: 'Never invent class or token names',
    text: 'Use only the classes, modifiers, elements, data-state values and tokens listed in this file. If something is missing, write custom CSS with existing tokens instead of guessing a name such as c-button--warning.',
  },
  {
    id: 'states',
    title: 'States use data-state plus the native or ARIA pair',
    text: 'Express component state with data-state="…" (for example data-state="error"), and always add the paired native attribute or ARIA listed for that state (disabled, aria-invalid, aria-busy).',
  },
  {
    id: 'theming',
    title: 'Theme with semantic tokens, never raw values',
    text: 'Never hard-code colors (#hex, rgb()) or pixel spacing. Use semantic tokens (--color-text-default, --color-action-primary…) or component tokens (--button-primary-background…). Primitive color tokens (--color-gray-*, --color-blue-*) do not adapt to dark mode.',
  },
];

const THEMES = {
  attribute: 'data-theme',
  default: 'light',
  values: {
    light: 'Light theme. Also the default when no data-theme attribute is set.',
    dark: 'Dark theme.',
    auto: 'Follows the operating system via prefers-color-scheme.',
  },
};

const FIGMA_TYPES = new Set(['color', 'dimension', 'number', 'fontWeight', 'duration']);

export function generate(root) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const { sets } = loadTokens(join(root, 'tokens'));
  const byMode = Object.fromEntries(MODES.map((m) => [m, tokensForMode(sets, m)]));
  const contracts = loadContracts(join(root, 'components'));
  const examples = new Map(contracts.map((c) => [c.block, loadExamples(join(root, 'components'), c)]));

  const tokenRows = buildTokenRows(sets, byMode);
  const manifest = buildManifest(pkg, tokenRows, contracts, examples);

  const files = new Map();
  const tokensCss = buildCss(sets, byMode);
  files.set('src/tokens.css', tokensCss);
  files.set('dist/mcss-lite.css', buildBundle(root, pkg, tokensCss));
  for (const [name, content] of buildFigma(sets)) files.set(`dist/figma/${name}`, content);
  files.set('dist/figma/push-variables.js', buildFigmaScript(pkg, sets));
  files.set('dist/mcss-lite.manifest.json', JSON.stringify(manifest, null, 2) + '\n');

  const docs = buildDocs(pkg, tokenRows, contracts, examples);
  files.set('AGENTS.md', docs.agents);
  files.set('llms.txt', docs.index);
  files.set('llms-components.txt', docs.components);
  files.set('llms-tokens.txt', docs.tokens);
  files.set('llms-full.txt', docs.full);
  files.set('demo/index.html', buildDemo(root, pkg, contracts, tokenRows));
  return files;
}

// ---------- CSS ----------

function buildCss(sets, byMode) {
  const light = byMode.light;
  const decls = (list, byPath) => list.map((t) => `  ${t.name}: ${tokenToCss(t, byPath)};`).join('\n');
  const block = (selector, body) => `${selector} {\n${body}\n}\n`;
  const themed = (mode) => [
    `  color-scheme: ${mode};`,
    decls(sets[mode], byMode[mode]),
    '',
    '  /* Component tokens are re-declared per theme so their var() references resolve in this scope. */',
    decls(sets.component, byMode[mode]),
  ].join('\n');

  return [
    '/* ============================================================',
    '   MCSS-Lite: Design Tokens',
    '   GENERATED by scripts/build.mjs from tokens/*.tokens.json.',
    '   Do not edit this file. Edit the JSON and run `npm run build`.',
    '',
    '   Themes: light (default), [data-theme="dark"], and',
    '   [data-theme="auto"] which follows prefers-color-scheme',
    '   (light unless the OS asks for dark, also when nested).',
    '   ============================================================ */',
    '',
    block(':root', ['  /* === Primitives === */', decls(sets.primitive, light), '', '  /* === Semantic (all themes) === */', decls(sets.semantic, light)].join('\n')),
    block(':root,\n[data-theme="light"],\n[data-theme="auto"]', themed('light')),
    block('[data-theme="dark"]', themed('dark')),
    indented('@media (prefers-color-scheme: dark)', block('[data-theme="auto"]', themed('dark'))),
    '/* Print always uses the light theme. */',
    indented('@media print', block(':root,\n[data-theme]', themed('light'))),
  ].join('\n');
}

function indented(atRule, body) {
  return `${atRule} {\n${body.trimEnd().split('\n').map((l) => (l ? '  ' + l : l)).join('\n')}\n}\n`;
}

// One file, no @import waterfall: layer order, tokens, then each layer. Comments stripped.
const CSS_PARTS = ['global.css', 'layout.css', 'components.css', 'utilities.css'];
function buildBundle(root, pkg, tokensCss) {
  const strip = (css) => css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\n\s*\n+/g, '\n').trim();
  const parts = [tokensCss, ...CSS_PARTS.map((f) => readFileSync(join(root, 'src', f), 'utf8'))];
  return [
    `/* ${pkg.name}@${pkg.version} | ${pkg.license} | generated bundle of index.css */`,
    '@layer global, layout, component, utility;',
    ...parts.map(strip),
    '',
  ].join('\n');
}

// ---------- Token rows (manifest + docs) ----------

function buildTokenRows(sets, byMode) {
  const row = (t, extra = {}) => ({
    name: t.name,
    path: t.path,
    tier: t.tier,
    type: resolveType(t, byMode.light),
    ...(isAlias(t.value) && { alias: byMode.light.get(aliasPath(t.value)).name }),
    ...extra,
    ...(t.description && { description: t.description }),
    ...(t.deprecated && { deprecated: t.deprecated }),
    figma: !isFigmaExcluded(t) && FIGMA_TYPES.has(resolveType(t, byMode.light)),
  });
  const rows = [];
  for (const t of sets.primitive) rows.push(row(t, { value: resolvedCss(t, byMode.light) }));
  for (const t of sets.semantic) rows.push(row(t, { value: resolvedCss(t, byMode.light) }));
  sets.light.forEach((t, i) => {
    const d = sets.dark[i];
    rows.push({
      ...row(t, { value: { light: resolvedCss(t, byMode.light), dark: resolvedCss(d, byMode.dark) } }),
      ...(isAlias(t.value) && { alias: { light: byMode.light.get(aliasPath(t.value)).name, dark: byMode.dark.get(aliasPath(d.value)).name } }),
    });
  });
  for (const t of sets.component) {
    const light = resolvedCss(t, byMode.light);
    const dark = resolvedCss(t, byMode.dark);
    rows.push(row(t, { value: light === dark ? light : { light, dark } }));
  }
  return rows;
}

function resolveType(t, byPath) {
  let cur = t;
  const seen = new Set();
  while (!cur.type && isAlias(cur.value) && !seen.has(cur.path)) {
    seen.add(cur.path);
    cur = byPath.get(aliasPath(cur.value));
  }
  return cur.type;
}

// ---------- Manifest ----------

function buildManifest(pkg, tokenRows, contracts, examples) {
  return {
    name: pkg.name,
    version: pkg.version,
    description: pkg.description,
    generatedFrom: ['tokens/*.tokens.json', 'components/*.json'],
    cascade: ['global', 'layout', 'component', 'utility'],
    prefixes: { 'l-': 'layout primitive', 'c-': 'component', 'u-': 'utility' },
    naming: 'BEM: block, block__element, block--modifier. State: data-state="value" on the block.',
    themes: THEMES,
    rules: RULES,
    blocks: contracts.map(({ file, $schema, ...c }) => ({
      ...c,
      examples: (examples.get(c.block) ?? []).map((e) => ({ file: `components/${e.file}`, html: e.html })),
    })),
    tokens: tokenRows,
  };
}

// ---------- Figma ----------

// Figma natively imports DTCG JSON, one file per collection/mode. It does not support composite
// types (shadow, typography), so those stay code-only. rem dimensions are converted to px.
function buildFigma(sets) {
  const allExcluded = new Set(
    [...sets.primitive, ...sets.semantic, ...sets.light, ...sets.component].filter(isFigmaExcluded).map((t) => t.path),
  );
  const figmaScopes = (t, type) => {
    if (t.extensions['com.figma.scopes']) return t.extensions['com.figma.scopes'];
    const p = t.path;
    if (p.startsWith('space.')) return ['GAP', 'WIDTH_HEIGHT'];
    if (p.startsWith('border-radius.') || p.endsWith('.radius')) return ['CORNER_RADIUS'];
    if (p.startsWith('border-width.')) return ['STROKE_FLOAT'];
    if (p.startsWith('font.size.')) return ['FONT_SIZE'];
    if (p.startsWith('font.weight.')) return ['FONT_WEIGHT'];
    if (p.startsWith('container.')) return ['WIDTH_HEIGHT'];
    if (type === 'color') return ['ALL_FILLS', 'STROKE_COLOR'];
    return [];
  };
  const figmaPath = (path) => path.replace(/\$root/g, 'default');
  const figmaValue = (type, v) => {
    if (typeof v === 'string' && isAlias(v)) return `{${figmaPath(aliasPath(v))}}`;
    if (type === 'dimension') return v.unit === 'rem' ? { value: +(v.value * 16).toFixed(3), unit: 'px' } : v;
    if (type === 'duration') return v.value;
    return v;
  };
  const figmaType = (type) => (type === 'fontWeight' || type === 'duration' ? 'number' : type);

  const tree = (lists, byPath) => {
    const root = {};
    for (const t of lists.flat()) {
      if (isFigmaExcluded(t)) continue;
      if (isAlias(t.value) && allExcluded.has(aliasPath(t.value))) continue;
      const type = resolveType(t, byPath);
      if (!FIGMA_TYPES.has(type)) continue;
      const segs = figmaPath(t.path).split('.');
      let node = root;
      for (const s of segs.slice(0, -1)) node = node[s] ??= {};
      node[segs.at(-1)] = {
        $type: figmaType(type),
        $value: figmaValue(type, t.value),
        ...(t.description && { $description: t.description }),
        $extensions: { 'com.figma.scopes': figmaScopes(t, type) },
      };
    }
    return JSON.stringify(root, null, 2) + '\n';
  };

  const light = tokensForMode(sets, 'light');
  const dark = tokensForMode(sets, 'dark');
  return [
    ['primitive.tokens.json', tree([sets.primitive], light)],
    ['semantic.light.tokens.json', tree([sets.semantic, sets.light], light)],
    ['semantic.dark.tokens.json', tree([sets.semantic, sets.dark], dark)],
    ['component.tokens.json', tree([sets.component], light)],
  ];
}

// ---------- Docs ----------

const fence = (lang, s) => '```' + lang + '\n' + s + '\n```';
const fmtValue = (v) => (typeof v === 'object' ? `${v.light} / ${v.dark}` : v);

function buildDocs(pkg, tokenRows, contracts, examples) {
  const header = (title, what) => [
    `# ${title}`,
    '',
    `> ${what}`,
    `> Generated from tokens/*.tokens.json and components/*.json by scripts/build.mjs. Do not edit by hand.`,
    `> Package: ${pkg.name}@${pkg.version}`,
    '',
  ].join('\n');

  const rulesMd = [
    '## Rules',
    '',
    ...RULES.map((r, i) => `${i + 1}. **${r.title}.** ${r.text}`),
    '',
  ].join('\n');

  const setupMd = [
    '## Setup',
    '',
    fence('html', `<link rel="stylesheet" href="node_modules/${pkg.name}/index.css">\n<html data-theme="auto"> <!-- optional: light (default) | dark | auto -->`),
    '',
    'Cascade layers, lowest to highest: `@layer global, layout, component, utility;`. Prefixes: `l-` layout primitive, `c-` component, `u-` utility. Naming is BEM: `c-block`, `c-block__element`, `c-block--modifier`; state is `data-state="value"` on the block.',
    '',
    'Before finishing, check your markup:',
    '',
    fence('sh', 'npx mcss-lite validate path/to/file.html   # or a directory; add --json for machine output'),
    '',
  ].join('\n');

  const blocksTable = [
    '## Blocks at a glance',
    '',
    '| Class | Layer | Modifiers | Elements | data-state | Use for |',
    '|---|---|---|---|---|---|',
    ...contracts.filter((c) => c.layer !== 'utility').map((c) => {
      const mods = (c.modifiers ?? []).map((m) => m.values.map((v) => `--${v.name}`).join(' ')).join(' · ') || '—';
      const els = (c.elements ?? []).map((e) => `__${e.name}`).join(' ') || '—';
      const states = (c.states ?? []).map((s) => s.name).join(' ') || '—';
      const status = c.status === 'deprecated' ? ` **Deprecated → \`${c.replacement}\`.**` : '';
      return `| \`${c.block}\` | ${c.layer} | ${mods} | ${els} | ${states} | ${firstSentence(c.description)}${status} |`;
    }),
    '',
  ].join('\n');

  const utilities = contracts.find((c) => c.layer === 'utility');
  const utilitiesMd = utilities ? [
    '## Utilities',
    '',
    utilities.description,
    '',
    ...utilities.classes.map((u) => `- \`${u.name}\`: ${u.description}`),
    '',
  ].join('\n') : '';

  const blockDetail = (c) => {
    const out = [`### ${c.name} — \`${c.block}\``, ''];
    if (c.status === 'deprecated') out.push(`**Deprecated.** Use \`${c.replacement}\` instead.`, '');
    out.push(c.description, '');
    if (c.tags) out.push(`**Apply to:** ${c.tags.map((t) => `\`<${t}>\``).join(', ')}`, '');
    for (const m of c.modifiers ?? []) {
      out.push(`**Modifiers — ${m.group}** (${m.exclusive ? 'pick at most one' : 'combinable'}):`);
      for (const v of m.values) out.push(`- \`${c.block}--${v.name}\`: ${v.description}`);
      out.push('');
    }
    if (c.elements?.length) {
      out.push('**Elements:**');
      for (const e of c.elements) out.push(`- \`${c.block}__${e.name}\`${e.required ? ' (required)' : ''}: ${e.description}${e.tags ? ` On ${e.tags.map((t) => `\`<${t}>\``).join('/')}.` : ''}`);
      out.push('');
    }
    if (c.states?.length) {
      out.push('**States:**');
      for (const s of c.states) out.push(`- \`data-state="${s.name}"\`: ${s.description}${s.pair ? ` ${s.pair}` : ''}`);
      out.push('');
    }
    if (c.customProperties?.length) {
      out.push('**Custom properties:**');
      for (const p of c.customProperties) out.push(`- \`${p.name}\` (default \`${p.default}\`): ${p.description}`);
      out.push('');
    }
    if (c.children?.length) out.push('**Structure:**', ...c.children.map((x) => `- ${x}`), '');
    if (c.guidelines?.use?.length) out.push('**Do:**', ...c.guidelines.use.map((x) => `- ${x}`), '');
    if (c.guidelines?.avoid?.length) out.push("**Don't:**", ...c.guidelines.avoid.map((x) => `- ${x}`), '');
    if (c.a11y?.length) out.push('**Accessibility:**', ...c.a11y.map((x) => `- ${x}`), '');
    if (c.tokens?.length) out.push(`**Tokens:** ${c.tokens.map((t) => `\`${t}\``).join(', ')}`, '');
    for (const e of examples.get(c.block) ?? []) {
      if (e.html) out.push(`**Example** (\`components/${e.file}\`):`, '', fence('html', e.html), '');
    }
    return out.join('\n');
  };

  const componentsMd = [
    '## Layout primitives',
    '',
    ...contracts.filter((c) => c.layer === 'layout').map(blockDetail),
    '## Components',
    '',
    ...contracts.filter((c) => c.layer === 'component').map(blockDetail),
    utilitiesMd,
  ].join('\n');

  const semanticRows = tokenRows.filter((t) => t.tier === 'semantic');
  const group = (rows, keyFn) => rows.reduce((m, r) => m.set(keyFn(r), [...(m.get(keyFn(r)) ?? []), r]), new Map());
  const intentOf = (r) => (r.path.startsWith('color.') ? r.path.split('.').slice(0, 2).join('.') : r.path.split('.')[0]);
  const INTENT_TITLES = {
    'color.text': 'Text', 'color.background': 'Backgrounds', 'color.border': 'Borders',
    'color.action': 'Actions', 'color.focus-ring': 'Focus', space: 'Spacing (semantic)',
  };
  const themesMd = [
    '## Themes',
    '',
    'Set `data-theme` on `<html>` or any subtree: `light` (default when absent), `dark`, or `auto` (follows the OS). Only semantic tokens change between themes; component tokens alias semantic ones, so they follow automatically.',
    '',
    'To theme for a brand, override semantic tokens, for example:',
    '',
    fence('css', ':root, [data-theme="light"] { --color-action-primary: #7a2e8f; }\n[data-theme="dark"] { --color-action-primary: #d9a6e8; }'),
    '',
  ].join('\n');
  const semanticMd = [
    '## Semantic tokens (use these)',
    '',
    'Values are shown as light / dark.',
    '',
    ...[...group(semanticRows, intentOf)].flatMap(([intent, rows]) => [
      `### ${INTENT_TITLES[intent] ?? intent}`,
      '',
      '| Token | Value | Use for |',
      '|---|---|---|',
      ...rows.map((r) => `| \`${r.name}\` | ${fmtValue(r.value)} | ${r.description ?? ''} |`),
      '',
    ]),
  ].join('\n');
  const scalesMd = [
    '## Scales (primitives safe to use anywhere)',
    '',
    ...[...group(tokenRows.filter((t) => t.tier === 'primitive' && t.type !== 'color'), (r) => r.path.split('.').slice(0, r.path.startsWith('font.') ? 2 : 1).join('.'))].map(([g, rows]) =>
      `- **${g}:** ${rows.map((r) => `\`${r.name}\` (${r.value})`).join(', ')}`),
    '',
  ].join('\n');
  const componentTokensMd = [
    '## Component tokens',
    '',
    'Override one of these to restyle a single component without affecting others.',
    '',
    '| Token | Aliases | Value |',
    '|---|---|---|',
    ...tokenRows.filter((t) => t.tier === 'component').map((r) => `| \`${r.name}\` | \`${r.alias}\` | ${fmtValue(r.value)} |`),
    '',
  ].join('\n');
  const primitiveColorsMd = [
    '## Primitive colors (do not use in components)',
    '',
    'These are the raw palette behind the semantic tokens. They do not change with the theme. Use them only to define your own semantic tokens.',
    '',
    tokenRows.filter((t) => t.tier === 'primitive' && t.type === 'color').map((r) => `\`${r.name}\``).join(', '),
    '',
  ].join('\n');
  const tokensMd = [themesMd, semanticMd, scalesMd, componentTokensMd, primitiveColorsMd].join('\n');

  const agents = [
    header('MCSS-Lite: guide for AI coding agents', 'How to build UI with MCSS-Lite: the rules, every class, every token. Read this before writing markup or CSS.'),
    rulesMd,
    setupMd,
    blocksTable,
    '## More detail',
    '',
    '- `llms-components.txt`: every block with modifiers, elements, states, accessibility rules and a canonical example.',
    '- `llms-tokens.txt`: every token with light and dark values.',
    '- `dist/mcss-lite.manifest.json`: the same data as JSON.',
    '',
    themesMd,
    semanticMd,
    scalesMd,
  ].join('\n');

  const components = [header('MCSS-Lite components', 'Every layout primitive, component and utility, with canonical examples.'), rulesMd, componentsMd].join('\n');
  const tokens = [header('MCSS-Lite tokens', 'Every design token with light and dark values.'), tokensMd].join('\n');
  const full = [header('MCSS-Lite (full)', 'Rules, components and tokens in one file.'), rulesMd, setupMd, blocksTable, componentsMd, tokensMd].join('\n');

  const index = [
    '# MCSS-Lite',
    '',
    `> ${pkg.description} Pure CSS: design tokens, l-* layout primitives, c-* BEM components with data-state, u-* utilities. Light, dark and auto themes.`,
    '',
    'Key rules: components never set outer margin (layouts space them); never invent class or token names; states are data-state plus ARIA; use semantic tokens, never raw colors. Validate markup with `npx mcss-lite validate <path>`.',
    '',
    '## Docs',
    '',
    '- [AGENTS.md](AGENTS.md): rules, setup, all blocks at a glance, semantic tokens',
    '- [Components](llms-components.txt): every block with modifiers, elements, states, a11y and examples',
    '- [Tokens](llms-tokens.txt): every token with light and dark values',
    '- [Manifest](dist/mcss-lite.manifest.json): machine-readable tokens and contracts',
    '',
    '## Optional',
    '',
    '- [Full](llms-full.txt): everything above in one file',
    '- [Figma tokens](dist/figma/): DTCG files for native Figma Variables import',
    '',
  ].join('\n');

  return { agents, index, components, tokens, full };
}

const firstSentence = (s) => s.split(/(?<=\.)\s/)[0];
